name: Build Resume

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-extra make

      - name: Create output directory
        run: mkdir -p output

      - name: Build HTML
        run: make html

      - name: Build DOCX
        run: make docx

      - name: Build PDF
        run: make pdf

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v2
        with:
          name: HTML
          path: output/GiangNH_resume.html

      - name: Upload DOCX artifact
        uses: actions/upload-artifact@v2
        with:
          name: DOCX
          path: output/GiangNH_resume.docx

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: output/GiangNH_resume.pdf