name: Convert Markdown

on:
  push:
    paths:
      - 'build/**/*.md'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04

    steps:
      # Check out the repository to the GitHub Actions runner
      - name: Checkout repository
        uses: actions/checkout@v2

      # Find the latest .md file in the build directory
      - name: Find latest markdown file in build
        id: find_md
        run: |
          md_file=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -E '^build/.*\.md$' | head -n 1)
          echo "::set-output name=md_file::$md_file"

      # Convert .md file to .pdf
      - name: Convert Markdown to PDF
        if: steps.find_md.outputs.md_file != ''
        uses: docker://pandoc/core:2.9
        with:
          args: "${{ steps.find_md.outputs.md_file }} -o build/output.pdf"

      # Convert .md file to .docx
      - name: Convert Markdown to DOCX
        if: steps.find_md.outputs.md_file != ''
        uses: docker://pandoc/core:2.9
        with:
          args: "${{ steps.find_md.outputs.md_file }} -o build/output.docx"

      # Convert .md file to HTML
      - name: Convert Markdown to HTML
        if: steps.find_md.outputs.md_file != ''
        uses: docker://pandoc/core:2.9
        with:
          args: "${{ steps.find_md.outputs.md_file }} -o build/output.html"

      # Upload the artifacts
      - name: Upload converted files
        uses: actions/upload-artifact@v2
        with:
          name: converted-files
          path: |
            build/output.pdf
            build/output.docx
            build/output.html
