name: Convert Markdown to PDF and DOCX

on: [push]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create output directories
        run: |
          mkdir -p output/pdf
          mkdir -p output/docx

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: '**/*.md'

      - name: Convert MD to PDF and DOCX
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            ${{ steps.changed-files.outputs.all_changed_files }}
            -o output/pdf/output.pdf
            --pdf-engine=xelatex

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: output/pdf

      - name: Upload DOCX artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DOCX
          path: output/docx